---
title: "Human Genome Analysis Spring 2024"
---

This is a rendering of hmtl files from the [course repository](https://github.com/jeffreyblanchard/HumGen2024R) for Human Genome Analysis taught at the University of Massachusetts Amherst by Prof. Jeffrey Blanchard.  If you are not using RStudio (Posit) Cloud here are [directions](HumGen_github.html) for creating a RStudio project space that will sync with and download files from the course repo.

Introduction to R and Tidyverse

* Lab 1 : [Introduction to R and Reproducible Research](HumGen_Lab1_intro.html)
* Lab 2 : [Data Visualization with ggplot](HumGen_Lab2_ggplot.html)
* Lab 3 : [Data Transformation with dplyr](HumGen_Lab3_trans.html)
* Lab 5 : [Data Transformation and Visualization with COVID-19 Reporting Data](HumGen_Lab5_covid.html)
* Lab 8 : [Data Tidying and Transformation with Table Joins](HumGen_Lab8_joins.html)

Genetic testing, SNPs and GWAS

* Lab 4 : [Data Transformation and Visualization with 23andMe data](HumGen_Lab4_23andMe.html)
* Lab 6 : [Organizing DTC Genetic Testing Reports and Finding your Genealogical Ancestors](HumGen_Lab6_genealogical_ancestors.html)
* Lab 7 : [How Many Genetic Ancestors Do I Have?"](HumGen_Lab7_genetic_ancestors.html)
* Lab 9 : [Data Transformation and Visualization with GWASCAT mappings I](HumGen_Lab9_gwascat1.html)
* Lab 10 : [Data Transformation and Visualization with GWASCAT mappings II](HumGen_Lab10_gwascat2.html)

Gene Expression Analysis

* Lab 11 : [RNAseq - Normalization and Data Exploration](HumGen_Lab11_rnaseq.html)

Special labs for graduates students in 678

* Lab g1 : [Mapping the COVID-19 Reporting Data](HumGen_Labg1_covid_map.html)
* Lab g2 : [Connecting a Github Repo Site with a RStudio Project](HumGen_Labg2_github.html)
